### ISSUE TITLE
没明白你这个用于什么功能？

### ISSUE THREAD

**Issue by jj89757hhb** [Neojoke/WLRRoute#2]

**Comment by huangboju** [comment]
@hhb19900618 界面跳转解耦啊。比如你用nav跳转A->B。那么A和B必须依赖。但是你引入一个Route，就变成了A->Route->B,A跟B没有任何依赖。可以看看这个[视频](http://www.infoq.com/cn/presentations/the-road-of-mobile-tmall-decoupling)
