### ISSUE TITLE
只能用于app内部吗？

### ISSUE THREAD

**Issue by hs-qingzhi** [Neojoke/WLRRoute#3]
能否在某个网页中打开app的某个具体界面，比如（detailViewcontroller）。

**Comment by Neojoke** [comment]
@AlvinBoy 可以，需要将网页中要打开的Url取出传递给路由实体

**Comment by AlvinBoy** [comment]
我说的在不用的app 中，或是safari中的网页。

**Comment by hs-qingzhi** [comment]
@Neojoke 我说的在不用的app 中，或是safari中的网页。

**Comment by Yincongxiao** [comment]
你好,如果两个界面之间传递的值是自定义的模型类,那请问如何通过url的方式将参数封装起来传递呢?

**Comment by Neojoke** [comment]
@Yincongxiao 需要转换为字典传递
