### ISSUE TITLE
所有页面都跳转是否需要注册所有页面的handler

### ISSUE THREAD

**Issue by fss1994** [Neojoke/WLRRoute#6]
楼主你好, 我想问一下, 如果要实现项目内全部跳转, 是否意味着要把所有界面都注册一个handler, 是不是可以考虑用反射机制来做?

**Comment by Neojoke** [comment]
@fss1994 反射倒是用不上，所有的界面实例的初始化有两种：1.storyboard 2.代码初始化，根据配置文件来标识每一个视图控制器的初始化参数，直接在handler层里读取配置初始化每个界面，在配置文件中可以配置url与对应的视图控制器就可以了。

**Comment by fss1994** [comment]
您的意思还是需要多个handler吗?如果是的话并没有区别啊,N个界面需要跳转,就需要注册N个handler

**Comment by Neojoke** [comment]
简单点的话，可以是一个controller对应一个handler，但也可以一个handler来处理
`
-(UIViewController *)targetViewControllerWithRequest:(WLRRouteRequest *)request;{
    //在此可以通过request参数，和self.routeExpression来动态返回不同的目标控制器，那么仅仅只需要继承WLRRouteHandler就可以
}
-(BOOL)handleRequest:(WLRRouteRequest *)request error:(NSError *__autoreleasing *)error{
//来控制如何调用targetViewControllerWithRequest 与sourceViewControllerForTransitionWithRequest
}
-(BOOL)transitionWithWithRequest:(WLRRouteRequest *)request sourceViewController:(UIViewController *)sourceViewController targetViewController:(UIViewController *)targetViewController isPreferModal:(BOOL)isPreferModal error:(NSError *__autoreleasing *)error{
//可以在此自定义controller的转场
}
`

**Comment by Neojoke** [comment]
简单点的话，可以是一个controller对应一个handler，但也可以一个handler来处理
```
-(UIViewController *)targetViewControllerWithRequest:(WLRRouteRequest *)request;{
 //在此可以通过request参数，和self.routeExpression来动态返回不同的目标控制器，那么仅仅只需要继承WLRRouteHandler就可以 
}
 -(BOOL)handleRequest:(WLRRouteRequest *)request error:(NSError *__autoreleasing *)error{ 
//来控制如何调用targetViewControllerWithRequest 与sourceViewControllerForTransitionWithRequest } 
-(BOOL)transitionWithWithRequest:(WLRRouteRequest *)request sourceViewController:(UIViewController *)sourceViewController targetViewController:(UIViewController *)targetViewController isPreferModal:(BOOL)isPreferModal error:(NSError *__autoreleasing *)error{
 //可以在此自定义controller的转场 
}
```

**Comment by fss1994** [comment]
嗯,了解

**Comment by fss1994** [comment]
谢啦
